description: CCD User profile 
name: ccd-user-profile-api
apiVersion: v1
home: https://github.com/hmcts/ccd-user-profile-api
version: 1.4.1
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
